spring:
  r2dbc:
    url: r2dbc:h2:mem:///sportsdb;DB_CLOSE_DELAY=-1
    username: sa
    password:
  sql:
    init:
      mode: always
      schema-locations: classpath:/schema.sql

# Expose WebFlux routing endpoints
server:
  port: 8080